# Generated by Django 3.2.16 on 2023-03-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='mahsulot_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot'),
        ),
    ]
