# Generated by Django 3.2.16 on 2023-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_izoh_mahsulot_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
