# Generated by Django 3.2.16 on 2023-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_alter_izoh_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
