# Generated by Django 3.2.16 on 2023-03-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0002_tanlangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='chegirma',
        ),
    ]
